"""Stable profile schema, validation, and compatibility constants."""

from __future__ import annotations

from enum import StrEnum

from unity_ai_assets.core.version import (
    ASSET_TYPE_CATALOG_SCHEMA_NAME,
    ASSET_TYPE_CATALOG_SCHEMA_VERSION,
    GENERATION_PROFILE_SCHEMA_NAME,
    GENERATION_PROFILE_SCHEMA_VERSION,
    NEGATIVE_PROMPT_PROFILE_SCHEMA_NAME,
    NEGATIVE_PROMPT_PROFILE_SCHEMA_VERSION,
    PROMPT_TEMPLATE_SCHEMA_NAME,
    PROMPT_TEMPLATE_SCHEMA_VERSION,
    UNITY_IMPORT_PROFILE_CATALOG_SCHEMA_NAME,
    UNITY_IMPORT_PROFILE_CATALOG_SCHEMA_VERSION,
)

MAX_PROFILE_FILE_SIZE = 256_000
KNOWN_PLACEHOLDERS = frozenset({"subject", "style_modifiers", "asset_type"})
SEED_STRATEGIES = frozenset({"random", "fixed"})
PROFILE_ORIGINS = frozenset({"builtin", "user", "none"})


class CompatibilityState(StrEnum):
    """Overall compatibility state."""

    COMPATIBLE = "compatible"
    INCOMPATIBLE = "incompatible"


class ProfileErrorCode(StrEnum):
    """Stable profile subsystem errors."""

    PROFILE_SCHEMA_INVALID = "PROFILE_SCHEMA_INVALID"
    PROFILE_SCHEMA_UNSUPPORTED = "PROFILE_SCHEMA_UNSUPPORTED"
    PROFILE_ID_INVALID = "PROFILE_ID_INVALID"
    PROFILE_ID_DUPLICATE = "PROFILE_ID_DUPLICATE"
    PROFILE_BUILTIN_IMMUTABLE = "PROFILE_BUILTIN_IMMUTABLE"
    PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND"
    PROFILE_REFERENCE_INVALID = "PROFILE_REFERENCE_INVALID"
    PROFILE_TEMPLATE_NOT_FOUND = "PROFILE_TEMPLATE_NOT_FOUND"
    PROFILE_NEGATIVE_PROFILE_NOT_FOUND = "PROFILE_NEGATIVE_PROFILE_NOT_FOUND"
    PROFILE_IMPORT_PROFILE_NOT_FOUND = "PROFILE_IMPORT_PROFILE_NOT_FOUND"
    PROFILE_SERIALIZATION_FAILED = "PROFILE_SERIALIZATION_FAILED"
    PROFILE_PERSISTENCE_FAILED = "PROFILE_PERSISTENCE_FAILED"
    PROFILE_MIGRATION_REQUIRED = "PROFILE_MIGRATION_REQUIRED"
    PROFILE_MIGRATION_FAILED = "PROFILE_MIGRATION_FAILED"
    PROFILE_IMPORT_FAILED = "PROFILE_IMPORT_FAILED"
    PROFILE_EXPORT_FAILED = "PROFILE_EXPORT_FAILED"
    PROFILE_INCOMPATIBLE = "PROFILE_INCOMPATIBLE"
    PROFILE_CONFLICT = "PROFILE_CONFLICT"


class CompatibilityReasonCode(StrEnum):
    """Stable reasons a profile or resolved request is incompatible."""

    ASSET_TYPE_UNSUPPORTED = "ASSET_TYPE_UNSUPPORTED"
    OPERATION_UNSUPPORTED = "OPERATION_UNSUPPORTED"
    WIDTH_OUT_OF_RANGE = "WIDTH_OUT_OF_RANGE"
    HEIGHT_OUT_OF_RANGE = "HEIGHT_OUT_OF_RANGE"
    WIDTH_MULTIPLE_INVALID = "WIDTH_MULTIPLE_INVALID"
    HEIGHT_MULTIPLE_INVALID = "HEIGHT_MULTIPLE_INVALID"
    STEPS_OUT_OF_RANGE = "STEPS_OUT_OF_RANGE"
    GUIDANCE_OUT_OF_RANGE = "GUIDANCE_OUT_OF_RANGE"
    NEGATIVE_PROMPT_UNSUPPORTED = "NEGATIVE_PROMPT_UNSUPPORTED"
    IMPORT_PROFILE_UNKNOWN = "IMPORT_PROFILE_UNKNOWN"
    TEMPLATE_UNKNOWN = "TEMPLATE_UNKNOWN"
    NEGATIVE_PROFILE_UNKNOWN = "NEGATIVE_PROFILE_UNKNOWN"
    SCHEMA_VERSION_UNSUPPORTED = "SCHEMA_VERSION_UNSUPPORTED"
    SEED_OUT_OF_RANGE = "SEED_OUT_OF_RANGE"
    PROMPT_TOO_LONG = "PROMPT_TOO_LONG"
    NEGATIVE_PROMPT_TOO_LONG = "NEGATIVE_PROMPT_TOO_LONG"


__all__ = [
    "ASSET_TYPE_CATALOG_SCHEMA_NAME",
    "ASSET_TYPE_CATALOG_SCHEMA_VERSION",
    "GENERATION_PROFILE_SCHEMA_NAME",
    "GENERATION_PROFILE_SCHEMA_VERSION",
    "NEGATIVE_PROMPT_PROFILE_SCHEMA_NAME",
    "NEGATIVE_PROMPT_PROFILE_SCHEMA_VERSION",
    "PROMPT_TEMPLATE_SCHEMA_NAME",
    "PROMPT_TEMPLATE_SCHEMA_VERSION",
    "UNITY_IMPORT_PROFILE_CATALOG_SCHEMA_NAME",
    "UNITY_IMPORT_PROFILE_CATALOG_SCHEMA_VERSION",
    "CompatibilityReasonCode",
    "CompatibilityState",
    "ProfileErrorCode",
]
